### ISSUE TITLE
JWT : Unexpected control character found

### ISSUE THREAD

**Issue by leo91000** [getzincphp/zincphp#1]
Hi,

When I try to verify token with the following header :
**Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkcyI6eyJpZCI6MSwiaXNfYWRtaW4iOnRydWV9fQ.JRnQW50pPOvmwXQiKJCKnfzMMFvCPFzHggRBrdvWqwI**

```
<?php

try {
    $payload = App::JWT()->verify();
} catch (Exception $e) {
    App::response()->data(["error" => "You must provide token", "message" => $e->getMessage(), "file" => $e->getFile(), "line" => $e->getLine()])->status(404)->failed()->send();
}
```

I get the following error :
```
{
    "body": {
        "message": "Unexpected control character found",
        "file": "vendor\\firebase\\php-jwt\\src\\JWT.php",
        "line": 358
    },
    "status": 404,
    "content_type": "application/json",
    "status_type": "failed"
}
```

Am I doing something wrong ?

**Comment by rakibtg** [comment]
Hi @leo91000 
Sorry for the late reply. Let me apologize because the documentation is not up-to date with latest changes in the framework branch! 
Can you take a look at here: https://github.com/getzincphp/framework/blob/master/src/jwt/ZincJWT.php
Please let me know if you are facing any issue! I will try my best to complete the documentation ASAP but it's becoming very challenging for me to keep it going besides my fulltime job :(

**Comment by rakibtg** [comment]
Hi @leo91000
Sorry for the late reply. The documentation is not up-to date with latest changes in the framework repository!
Can you take a look at here: https://github.com/getzincphp/framework/blob/master/src/jwt/ZincJWT.php
Please let me know if you are facing any issue! I will try my best to complete the documentation ASAP!
